### ISSUE TITLE
C Compiler Issue

### ISSUE THREAD

**Issue by jstader** [geospace-code/georinex#60]
1. There are many types of RINEX files.
     Almost every issue is because of some corner case with a particular RINEX format.
     Thus we will usually need a copy of your RINEX file.
     If it's very large/private, consider copying just the part of it that causes the issue for you.
2. Please copy and paste the error traceback, to help find which function the error is occurring in.
3. generally a dump of all the versions of Python packages you have is **not** needed

ReadRinex rinex_files/brest_france/20191022_BRST00FRA_R_20192950000_01D_30S_MO.crx -u G -m S1C -v
cc /usr/local/lib/python3.7/site-packages/georinex/rnxcmp/source/crx2rnx.c -o /usr/local/lib/python3.7/site-packages/georinex/rnxcmp/crx2rnx
ld: can't open output file for writing '/usr/local/lib/python3.7/site-packages/georinex/rnxcmp/crx2rnx.ld_Qso3hq', errno=13 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gcc /usr/local/lib/python3.7/site-packages/georinex/rnxcmp/source/crx2rnx.c -o /usr/local/lib/python3.7/site-packages/georinex/rnxcmp/crx2rnx
ld: can't open output file for writing '/usr/local/lib/python3.7/site-packages/georinex/rnxcmp/crx2rnx.ld_IaiMOI', errno=13 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang /usr/local/lib/python3.7/site-packages/georinex/rnxcmp/source/crx2rnx.c -o /usr/local/lib/python3.7/site-packages/georinex/rnxcmp/crx2rnx
ld: can't open output file for writing '/usr/local/lib/python3.7/site-packages/georinex/rnxcmp/crx2rnx.ld_NHyA2O', errno=13 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/usr/local/bin/ReadRinex", line 8, in <module>
    sys.exit(main())
  File "/usr/local/bin/ReadRinex.py", line 48, in main
    verbose=P.verbose, fast=P.strict, interval=P.interval)
  File "/usr/local/lib/python3.7/site-packages/georinex/base.py", line 66, in load
    verbose=verbose, fast=fast, interval=interval)
  File "/usr/local/lib/python3.7/site-packages/georinex/base.py", line 189, in rinexobs
    fast=fast, interval=interval)
  File "/usr/local/lib/python3.7/site-packages/georinex/obs3.py", line 76, in rinexobs3
    with opener(fn) as f:
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/georinex/io.py", line 61, in opener
    f = io.StringIO(opencrx(f))
  File "/usr/local/lib/python3.7/site-packages/georinex/hatanaka.py", line 51, in opencrx
    raise RuntimeError('could not build Hatanka converter. Do you have a C compiler?')
RuntimeError: could not build Hatanka converter. Do you have a C compiler?

I have the home-brew gcc installed but python is complaining I don't have a compiler?

**Comment by scivision** [comment]
It could be that you do not have "write" permission for the directory `/usr/local/lib/python3.7/site-packages/georinex/rnxcmp/`

from Terminal, are you able to do:

```sh
touch /usr/local/lib/python3.7/site-packages/georinex/rnxcmp/foo
```
and have that file "foo" created?
