### ISSUE TITLE
Microseconds Error in sp3 Reader

### ISSUE THREAD

**Issue by Shaylah-Maria** [geospace-code/georinex#64]
The time in the file is:
2018  9 23  0  2 37.63292462

Georinex is saving datetime as:
2018-9-23T00:02:37.063292  (incorrect)

instead of:
2018-9-23T00:02:37.63292  (correct)

See first data point entry:
<img width="523" alt="Screen Shot 2020-03-23 at 1 20 30 PM" src="https://user-images.githubusercontent.com/34075185/77358450-7dc1a080-6d0f-11ea-89b9-0583e6c09aaf.png">

What is stored inside georinex.to_datetime(data.time[ii]) (first element of the saved dates in sp3 file). this should equal the first date point in file above:
![image](https://user-images.githubusercontent.com/34075185/77358588-c1b4a580-6d0f-11ea-93e2-9160cebe67e7.png)

To fix, must multiply what is saved in microseconds by 10.

-Shaylah Mutschler

**Comment by scivision** [comment]
Thank you I seem to have overlooked this. I have flagged this so I can examine and fix. Thanks for your patience and kindly feedback.

**Comment by mauriciodev** [comment]
It seems that line 145 of sp3.py should have "ln[23:29]" instead of "ln[23:28]"

        microsecond=int(ln[23:29]),
