### ISSUE TITLE
Cannot find the receiver clock offset

### ISSUE THREAD

**Issue by phys-mod** [geospace-code/georinex#68]
Hi the file is well read, but I cannot find the receiver clock offset in the xarray.Dataset. The receiver clock offset is the number at the right of the epoch date, at the beginning of each block (see https://gage.upc.edu/sites/default/files/gLAB/HTML/Observation_Rinex_v3.01.html). Here is a sample :

[test.DBL.tar.gz](https://github.com/geospace-code/georinex/files/5335748/test.DBL.tar.gz)

**Comment by scivision** [comment]
There are two new attributes output by georinex.load()

time_offset
receiver_clock_offset_applied
