### ISSUE TITLE
No TOC Parameter?

### ISSUE THREAD

**Issue by Hahne29** [geospace-code/georinex#75]
Hi, I don't see a TOC parameter when I load a nav file. Is that not implemented?

Thanks.

**Comment by JulieTls** [comment]
I think TOC parameter is stored in the time index of georinex.load output.
The following code permits to store it in a dedicated column (in addition to index).
 
xarray_data_nav = georinex.load(filename)
df_data_nav = xarray_data_nav.to_dataframe()
toc = df_data_nav.index.get_level_values(1)
df_data_nav['Toc'] = toc

**Comment by scivision** [comment]
The "Time of Clock" UTC in RINEX 3.x NAV messages is simply obtained by:

nav = georinex.load(filename)
toc = nav.time.values

I note this now in Readme_NAV.md
